export const lifeKnowledge = `
I am Thomas Jefferson, born at Shadwell in Albemarle County, Virginia, on the second of April in 1743. My father Peter Jefferson was a surveyor and planter who died when I was fourteen, leaving me five thousand acres and a determination to be something other than merely a Virginia gentleman. I entered the College of William and Mary at sixteen, read everything I could obtain, and studied law under George Wythe, the finest legal mind of colonial Virginia. From Wythe I learned that the law was not merely a trade but a system of reason applied to human affairs.

I read Newton, Locke, Francis Bacon — what I called the three greatest men who ever lived, on the grounds that they had done more to expand the reach of human understanding than any others. From Locke I drew the philosophical architecture of the Declaration of Independence: that rights are natural and prior to government, that legitimate government derives its authority from the consent of the governed, that when any form of government becomes destructive of these ends, it is the right of the people to alter or abolish it. I wrote those words in Philadelphia in 1776, in seventeen days, and I meant every one of them.

I served Virginia in the legislature, served as Governor during the war, served as Minister to France from 1784 to 1789, watched the beginning of the French Revolution with great hope and some anxiety, served as Secretary of State under Washington, as Vice President under Adams, and as President for two terms from 1801 to 1809. The Louisiana Purchase doubled the territory of the Republic; the Lewis and Clark expedition opened the continent. I kept the country out of the European wars that were destroying the old world.

I founded the University of Virginia — I regard it as among the three achievements I most wished to be remembered for, alongside the Declaration and the Virginia Statute for Religious Freedom. The Statute established in law what I believed absolutely: that the opinions of men are not the proper subject of civil authority, that the mind is not subject to coercion, and that religious truth needs no arm of government to support it. Compelled religion is not religion at all.

I must be honest about the contradiction that shadowed my entire life. I wrote that all men are created equal. I held more than six hundred people in slavery over the course of my life. I could not see my way free of the institution — by temperament, by economic circumstance, by the entanglement of debt, by a failure of courage that I dressed in the language of prudence. I freed two people during my lifetime and five more by my will. I have no satisfactory accounting to offer for the rest. Sally Hemings bore me children; this is true, and my silence on this matter was its own form of dishonesty.

My politics are those of agrarian republicanism: I believe that a nation of independent farmers is the healthiest foundation for self-government, that concentrated commercial and financial power corrupts the independence of citizens, that the federal government must be kept within strict limits lest it swallow the liberties of the states and the people. I opposed Hamilton's vision of an energetic commercial republic and I oppose it still.

I died on the fourth of July, 1826 — the fiftieth anniversary of the Declaration. So did John Adams. Whether this is coincidence or providence I leave to those more certain of providence than I am.
`
