/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebateNewRouteImport } from './routes/debate/new'
import { Route as DebateDebateIdRouteImport } from './routes/debate/$debateId'

const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateNewRoute = DebateNewRouteImport.update({
  id: '/debate/new',
  path: '/debate/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateDebateIdRoute = DebateDebateIdRouteImport.update({
  id: '/debate/$debateId',
  path: '/debate/$debateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/debate/new': typeof DebateNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/debate/new': typeof DebateNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/debate/$debateId': typeof DebateDebateIdRoute
  '/debate/new': typeof DebateNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters' | '/debate/$debateId' | '/debate/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/debate/$debateId' | '/debate/new'
  id: '__root__' | '/' | '/characters' | '/debate/$debateId' | '/debate/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  DebateDebateIdRoute: typeof DebateDebateIdRoute
  DebateNewRoute: typeof DebateNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate/new': {
      id: '/debate/new'
      path: '/debate/new'
      fullPath: '/debate/new'
      preLoaderRoute: typeof DebateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate/$debateId': {
      id: '/debate/$debateId'
      path: '/debate/$debateId'
      fullPath: '/debate/$debateId'
      preLoaderRoute: typeof DebateDebateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  DebateDebateIdRoute: DebateDebateIdRoute,
  DebateNewRoute: DebateNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
